name: Deploy Fixinator to Main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.STAGE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT_PROD }} -H vpn.leviathan.ateamservers.com >> ~/.ssh/known_hosts

      - name: Deploy plugin via rsync
        run: |
          rsync -avz --no-owner --no-perms --no-times --exclude='.*' -e "ssh -p ${{secrets.DEPLOY_PORT_PROD }}" \
            ./ \
            "${{ secrets.DEPLOY_USER }}@vpn.leviathan.ateamservers.com:/share/sites/gayety.com/htdocs/wp-content/plugins/smart feed fixinator/"
          ssh -t -p ${{ secrets.DEPLOY_PORT_PROD }} -i ~/.ssh/id_rsa -l ${{ secrets.DEPLOY_USER}} vpn.leviathan.ateamservers.com sudo /usr/local/ateam/sbin/ateam-repsync