name: Deploy Fixinator to Stage
on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.STAGE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT_STAGE }} -H vpn.leviathan.ateamservers.com >> ~/.ssh/known_hosts

      - name: Deploy plugin via rsync
        run: |
          rsync -avz --no-owner --no-perms --no-times --exclude='.*' -e "ssh -p ${{secrets.DEPLOY_PORT_STAGE }}" \
            ./ \
            "${{ secrets.DEPLOY_USER }}@vpn.leviathan.ateamservers.com:/share/sites/staging.gayety.com/htdocs/wp-content/plugins/smart feed fixinator/"
